services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ngapain-image
    container_name: ngapain-app
    volumes:
      - .:/var/www/html
    networks:
      - ngapain-network

  nginx:
    image: nginx:latest
    container_name: ngapain-nginx
    platform: linux/x86_64
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ngapain-network

  dbdocker:
    image: mysql:8.0
    container_name: ngapain-db
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ngapain
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ../ngapaindb:/var/lib/mysql
    networks:
      - ngapain-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ngapain-pma
    platform: linux/x86_64
    restart: always
    ports:
      - "8089:80"
    environment:
      PMA_HOST: ngapain-db
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - dbdocker
    networks:
      - ngapain-network

networks:
  ngapain-network:
